### PR TITLE
Translated ItemStacks stored in ItemStacks

### LINKED ISSUE #420: Custom projectile names display as raw translation keys
Image

Image

Description:
When using a crossbow loaded with any custom projectile from Pylon, the tooltip shows the raw translation key instead of the localized item name.
This happens with multiple projectile types (e.g. recoil_arrow, ice_arrow, etc.).

⚙️ Steps to Reproduce

Load a crossbow with a custom projectile (for example: ice_arrow or recoil_arrow).

Hover over the crossbow in your inventory.

Observe the tooltip text.

🖥️ Environment

Minecraft Version: 1.21.8

Server Type: Purpur

### LINKED ISSUE #549: Pylon items in shulker box won't display correct name
Image

### PR DESCRIPTION
**Pull request by Intybyte**
Fixes #549
Fixes #420

### CODE REVIEW

File: rebar/src/main/kotlin/io/github/pylonmc/rebar/i18n/PlayerTranslationHandler.kt [hunk 1]
```diff
@@ -15,6 +19,9 @@ import org.jetbrains.annotations.ApiStatus
 
 @ApiStatus.Internal
 class PlayerTranslationHandler internal constructor(private val player: Player) {
+    companion object {
+        val STOP_ADDING_THAT = rebarKey("stop_adding_that")
```
Comment (JustAHuman-xD) [inline rebar/src/main/kotlin/io/github/pylonmc/rebar/i18n/PlayerTranslationHandler.kt]: This should have a proper name lol
