### PR TITLE
Fix 222 with enhancements

### LINKED ISSUE #222: BlockListener cancelled specify BlockPlaceEvent accidentally
When I holds a Building Wand (my custom PylonItem) to trigger a FakeBlockPlaceEvent to check permission, the event was cancelled by BlockListener accidentally.

Image

Source Code:

Image

In this code, the Building Wand is never a placeable PylonItem. `pylonBlock` in this case is always null, the event always will be cancelled.

These are possible cases.

| Case | PylonItem placeable in design | Can trigger BlockPlaceEvent when use |  BlockListener's behavior |
| --- | --- | --- | --- |
| 1 | √ | √ | pass |
| 2 | √ | × | pass |
| 3 | × | √ | cancelled event |
| 4 | × | × | cancelled event |

Totally, BlockListener will handles BlockPlaceEvent incorrectly in case 3. Is there any method to avoid it without change the parameter `event.itemInHand`?

### PR DESCRIPTION
**Pull request by balugaq**
Closes #222 

Also took the chance to learn Kotlin, let me know if there's a better way to structure this :)

Main changes:
1. Fix #222 - See **BlockListener**, **NotPlaceable**
2. Check if the event is a fake event - See **BlockListener**, **PylonUtils**
3. Add comments in **PylonBlock**
4. Add **BlockCreateContext.PluginGenerate**, which is a different case of creating of PylonBlock.

### CODE REVIEW

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/util/PylonUtils.kt [hunk 1]
```diff
@@ -171,3 +172,7 @@ fun Component.withArguments(args: List<TranslationArgumentLike>): Component {
     }
     return result.children(result.children().map { it.withArguments(args) })
 }
+
+fun isFakeEvent(event: Event): Boolean {
+    return event.javaClass.name.contains("Fake");
```
Comment (OhmV-IR) [inline pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/util/PylonUtils.kt:177]: This is okay, but I think using an annotation class would be more clear & reliable.

**Review by OhmV-IR — COMMENTED** [review]
Not sure what these "fake" events are and where the classes for them are, can't find any in papermc and pretty sure there aren't any in pylon.

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/util/PylonUtils.kt (hunk 1 above)
Comment (balugaq) [reply pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/util/PylonUtils.kt:177]: Not only for Pylon, but also for other plugins

Case 1
https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/java/com/gmail/nossr50/events/fake

Case 2
https://github.com/Ghost-chu/QuickShop-Reremake/blob/dd52504e3271c91a8b4573c442a7174d2e743f39/src/main/java/org/maxgamer/quickshop/util/PermissionChecker.java#L134

But there's no case 2 check

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/block/PylonBlock.kt [hunk 2]
```diff
@@ -96,6 +115,10 @@ open class PylonBlock protected constructor(val block: Block) {
 
     /**
      * Called when the block is saved
+     *
+     * As known as `onSaveBlock`
```
Comment (Seggan) [inline pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/block/PylonBlock.kt:119]: It's not known as `onSaveBlock`, I would remove thi until we actually get around to renaming it

**Review by OhmV-IR — COMMENTED** [review]
Looks fine cw
