### PR TITLE
Fix vanilla translations

### LINKED ISSUE #152: Fix vanilla item names not being wrapped properly
`ItemStack#effectiveName()` returns a translatable component for vanilla items, and since those are translated clientside, we cannot do serverside translation for that. The solution would be to download the client translations ([which I've done before](https://github.com/Seggan/SpigotWorldGenVisualizer/blob/97f25184994fc24f51929f28f486f062fba06863/app/src/main/kotlin/io.github.seggan.swgv/App.kt#L54)) and manually hook those into the global translator so we can translate minecraft stuff serverside too.

### PR DESCRIPTION
**Pull request by Seggan**
Resolves #152

### CODE REVIEW

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+internal object MinecraftTranslator : Translator {
+
+    private const val LAUNCHER_META_URL = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"
+    private val LANG_REGEX = """^minecraft/lang/(.+)\.json$""".toRegex()
+
+    private val cacheDir = Path("cache/pylon/mclang")
+    private val translations = mutableMapOf<Locale, Map<String, MessageFormat>>()
+
+    init {
+        PylonCore.logger.info("Loading vanilla translations, this may take a while...")
```
Comment (LordIdra) [inline pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt:25]: Tiny thing but maybe 'but only needs to be done on the first run of Pylon'

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+import java.net.URI
+import java.nio.file.FileSystems
+import java.text.MessageFormat
+import java.util.Locale
+import kotlin.io.path.*
+
+internal object MinecraftTranslator : Translator {
+
+    private const val LAUNCHER_META_URL = "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json"
+    private val LANG_REGEX = """^minecraft/lang/(.+)\.json$""".toRegex()
```
Comment (LordIdra) [inline pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt:19]: What the fuck

**Review by LordIdra — COMMENTED** [review]
nice work, but think you couldadd a quick explanation at the top of MinecraftTranslator? it's very unclear to me what the file does at first glance. otherwise happy

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt (hunk 2 above)
Comment (Seggan) [reply pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt:19]: ? it's a regex for matching and extracting the lang files form the assets index

File: pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt (hunk 1 above)
Comment (LordIdra) [reply pylon-core/src/main/kotlin/io/github/pylonmc/pylon/core/i18n/MinecraftTranslator.kt:25]: Oh my bad

**Review by LordIdra — APPROVED** [review]
